// Export all services
export * from "./patient-service"
export * from "./doctor-service"
export * from "./nurse-service"
export * from "./staff-service"
export * from "./admin-service"
export * from "./admin-appointment-service"
export * from "./admin-report-service"
export * from "./manager-service"
export * from "./system-admin-service"
export * from "./emergency-service"
export * from "./payment-service"
// Explicitly export from insurance-service to resolve InsuranceProvider conflict
export type { InsuranceProvider as InsuranceProviderFromInsuranceService, InsuranceClaim } from "./insurance-service"
export { InsuranceService } from "./insurance-service"
export * from "./prescription-service"
export * from "./notification-service"
export * from "./user-service"
export * from "./report-service"
export * from "./pdf-report-service"